source {C:/Xilinx/data/projnav/scripts/VsimStopServer.tcl}
initIPC 1200
-- Auto Generated by Project Navigator to simulate
-- HDL Bencher Annotated Test Bench
--
vlib work
onbreak {resume}
onerror {quit -code 99 -force}
onElabError {resume}
vcom -93 -explicit  barrel_shifter_32bit.vhdl
vcom -93 -explicit  barrle_shifter_tb.ant
vsim -t 1ps  -lib work barrle_shifter_tb
run -all
quit -force
