# $Id$

CREATE TABLE Film(
	FilmID INTEGER NOT NULL AUTO_INCREMENT,
	FilmTitle VARCHAR(80) NOT NULL,
	FilmYear DATE NOT NULL,
	PRIMARY KEY(FilmID)
);

CREATE TABLE Actor(
	ActorID INTEGER NOT NULL AUTO_INCREMENT,
	ActorName VARCHAR(80) NOT NULL,
	ActorDOB DATE NOT NULL,
	PRIMARY KEY(ActorID)
);

CREATE TABLE FilmRole(
	Role VARCHAR(80) NULL,
	FilmID INTEGER NOT NULL AUTO_INCREMENT,
	ActorID INTEGER NOT NULL AUTO_INCREMENT,
	PRIMARY KEY(Role, FilmID, ActorID)
	FOREIGN KEY(FilmID) REFERENCES Film(FilmID),
	FOREIGN KEY(ActorID) REFERENCES Actor(ActorID),
);

CREATE TABLE Director(
	DirectorID INTEGER NOT NULL AUTO_INCREMENT,
	DirectorName VARCHAR(80) NOt NULL,
	DirectorDOB DATE NOT NULL,
	PRIMARY KEY(DirectorID)
);

CREATE TABLE Directed(
	FilmID INTEGER NOT NULL AUTO_INCREMENT,
	DirectorID INTEGER NOT NULL,
	PRIMARY KEY(FilmId, DirectorID)
	FOREIGN KEY(FilmID) REFERENCES Film(FilmID),
	FOREIGN KEY(DirectorID) REFERENCES Director(DirectorID)
);

CREATE TABLE Media(
	Barcode INTEGER NOT NULL AUTO_INCREMENT,
	Media VARCHAR(20) NOT NULL,
	Sound VARCHAR(20) NOt NULL,
	Region INTEGER(1) NOT NULL,
	AspectRatio VARCHAR(10) NOT NULL,
	PRIMARY KEY(Barcode)
);

CREATE TABLE MediaOptions(
	FilmID INTEGER NOT NULL,
	Barcode INTEGER NOT NULL,
	PRIMARY KEY(FilmID, Barcode),
	FOREIGN KEY (FilmID) REFERENCES Film(FIlmID),
	FOREIGN KEY (Barcode) REFERENCES Media(Barcode)
);
